# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Audio(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, blob_data: str=None, session_id: str=None, action_id: str=None, audio_language: str=None):  # noqa: E501
        """Audio - a model defined in Swagger

        :param blob_data: The blob_data of this Audio.  # noqa: E501
        :type blob_data: str
        :param session_id: The session_id of this Audio.  # noqa: E501
        :type session_id: str
        :param action_id: The action_id of this Audio.  # noqa: E501
        :type action_id: str
        :param audio_language: The audio_language of this Audio.  # noqa: E501
        :type audio_language: str
        """
        self.swagger_types = {
            'blob_data': str,
            'session_id': str,
            'action_id': str,
            'audio_language': str
        }

        self.attribute_map = {
            'blob_data': 'blobData',
            'session_id': 'sessionId',
            'action_id': 'actionId',
            'audio_language': 'audioLanguage'
        }
        self._blob_data = blob_data
        self._session_id = session_id
        self._action_id = action_id
        self._audio_language = audio_language

    @classmethod
    def from_dict(cls, dikt) -> 'Audio':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Audio of this Audio.  # noqa: E501
        :rtype: Audio
        """
        return util.deserialize_model(dikt, cls)

    @property
    def blob_data(self) -> str:
        """Gets the blob_data of this Audio.


        :return: The blob_data of this Audio.
        :rtype: str
        """
        return self._blob_data

    @blob_data.setter
    def blob_data(self, blob_data: str):
        """Sets the blob_data of this Audio.


        :param blob_data: The blob_data of this Audio.
        :type blob_data: str
        """

        self._blob_data = blob_data

    @property
    def session_id(self) -> str:
        """Gets the session_id of this Audio.


        :return: The session_id of this Audio.
        :rtype: str
        """
        return self._session_id

    @session_id.setter
    def session_id(self, session_id: str):
        """Sets the session_id of this Audio.


        :param session_id: The session_id of this Audio.
        :type session_id: str
        """

        self._session_id = session_id

    @property
    def action_id(self) -> str:
        """Gets the action_id of this Audio.


        :return: The action_id of this Audio.
        :rtype: str
        """
        return self._action_id

    @action_id.setter
    def action_id(self, action_id: str):
        """Sets the action_id of this Audio.


        :param action_id: The action_id of this Audio.
        :type action_id: str
        """

        self._action_id = action_id

    @property
    def audio_language(self) -> str:
        """Gets the audio_language of this Audio.


        :return: The audio_language of this Audio.
        :rtype: str
        """
        return self._audio_language

    @audio_language.setter
    def audio_language(self, audio_language: str):
        """Sets the audio_language of this Audio.


        :param audio_language: The audio_language of this Audio.
        :type audio_language: str
        """

        self._audio_language = audio_language
