# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Image(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, image_id: str=None, image_content: str=None,images_progress: str=None):  # noqa: E501
        """Image - a model defined in Swagger

        :param image_id: The image_id of this Image.  # noqa: E501
        :type image_id: str
        :param image_content: The image_content of this Image.  # noqa: E501
        :type image_content: str
        """
        self.swagger_types = {
            'image_id': str,
            'image_content': str,
            'images_progress': str
        }

        self.attribute_map = {
            'image_id': 'imageId',
            'image_content': 'imageContent',
            'images_progress': 'images_progress'
        }
        self._image_id = image_id
        self._image_content = image_content
        self._images_progress = images_progress

    @classmethod
    def from_dict(cls, dikt) -> 'Image':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Image of this Image.  # noqa: E501
        :rtype: Image
        """
        return util.deserialize_model(dikt, cls)

    @property
    def image_id(self) -> str:
        """Gets the image_id of this Image.


        :return: The image_id of this Image.
        :rtype: str
        """
        return self._image_id

    @image_id.setter
    def image_id(self, image_id: str):
        """Sets the image_id of this Image.


        :param image_id: The image_id of this Image.
        :type image_id: str
        """

        self._image_id = image_id

    @property
    def image_content(self) -> str:
        """Gets the image_content of this Image.


        :return: The image_content of this Image.
        :rtype: str
        """
        return self._image_content

    @image_content.setter
    def image_content(self, image_content: str):
        """Sets the image_content of this Image.


        :param image_content: The image_content of this Image.
        :type image_content: str
        """

        self._image_content = image_content

    @property
    def images_progress(self) -> str:
        """Gets the images_progress of this Images.


        :return: The images_progress of this Images.
        :rtype: List[Image]
        """
        return self._images_progress

    @images_progress.setter
    def images_progress(self, images_progress: str):
        """Sets the images_progress of this Images.

        :param images_progress: The images_progress of this Images.
        :type images_progress: str
        """

        self._images_progress = images_progress
