# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Prompt(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, prompt: str=None, session_id: str=None, action_id: str=None):  # noqa: E501
        """Prompt - a model defined in Swagger

        :param prompt: The prompt of this Prompt.  # noqa: E501
        :type prompt: str
        :param session_id: The session_id of this Prompt.  # noqa: E501
        :type session_id: str
        :param action_id: The action_id of this Prompt.  # noqa: E501
        :type action_id: str
        """
        self.swagger_types = {
            'prompt': str,
            'session_id': str,
            'action_id': str
        }

        self.attribute_map = {
            'prompt': 'prompt',
            'session_id': 'sessionId',
            'action_id': 'actionId'
        }
        self._prompt = prompt
        self._session_id = session_id
        self._action_id = action_id

    @classmethod
    def from_dict(cls, dikt) -> 'Prompt':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Prompt of this Prompt.  # noqa: E501
        :rtype: Prompt
        """
        return util.deserialize_model(dikt, cls)

    @property
    def prompt(self) -> str:
        """Gets the prompt of this Prompt.


        :return: The prompt of this Prompt.
        :rtype: str
        """
        return self._prompt

    @prompt.setter
    def prompt(self, prompt: str):
        """Sets the prompt of this Prompt.


        :param prompt: The prompt of this Prompt.
        :type prompt: str
        """

        self._prompt = prompt

    @property
    def session_id(self) -> str:
        """Gets the session_id of this Prompt.


        :return: The session_id of this Prompt.
        :rtype: str
        """
        return self._session_id

    @session_id.setter
    def session_id(self, session_id: str):
        """Sets the session_id of this Prompt.


        :param session_id: The session_id of this Prompt.
        :type session_id: str
        """

        self._session_id = session_id

    @property
    def action_id(self) -> str:
        """Gets the action_id of this Prompt.


        :return: The action_id of this Prompt.
        :rtype: str
        """
        return self._action_id

    @action_id.setter
    def action_id(self, action_id: str):
        """Sets the action_id of this Prompt.


        :param action_id: The action_id of this Prompt.
        :type action_id: str
        """

        self._action_id = action_id
