/* tslint:disable */
/* eslint-disable */
/**
 * Stability demo
 * Stability demo
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Audio
 */
export interface Audio {
    /**
     * 
     * @type {Blob}
     * @memberof Audio
     */
    blobData?: Blob;
    /**
     * 
     * @type {string}
     * @memberof Audio
     */
    sessionId?: string;
    /**
     * 
     * @type {string}
     * @memberof Audio
     */
    actionId?: string;
    /**
     * 
     * @type {string}
     * @memberof Audio
     */
    audioLanguage?: string;
}
