/* tslint:disable */
/* eslint-disable */
/**
 * Stability demo
 * Stability demo
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Image
 */
export interface Image {
    /**
     * 
     * @type {string}
     * @memberof Image
     */
    sessionId?: string;
    /**
     * 
     * @type {string}
     * @memberof Image
     */
    actionId?: string;
    /**
     * 
     * @type {string}
     * @memberof Image
     */
    imageId?: string;
    /**
     * 
     * @type {Blob}
     * @memberof Image
     */
    imageContent?: Blob;
}
