/* tslint:disable */
/* eslint-disable */
/**
 * Stability demo
 * Stability demo
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import type { Image } from './image';
/**
 * 
 * @export
 * @interface Images
 */
export interface Images {
    /**
     * 
     * @type {string}
     * @memberof Images
     */
    imagesArrayId?: string;
    /**
     * 
     * @type {Array<Image>}
     * @memberof Images
     */
    imageArrayContent?: Array<Image>;
}
