/* tslint:disable */
/* eslint-disable */
/**
 * Stability demo
 * Stability demo
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios from 'axios';
import type { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import type { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError } from '../base';
import type { RequestArgs } from '../base';
import type { Audio } from '../models';
import type { TextFromAudio } from '../models';
/**
 * AudioApi - axios parameter creator
 * @export
 */
export const AudioApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} audioId audioId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        audioAudioIdGet: async (audioId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'audioId' is not null or undefined
            if (audioId === null || audioId === undefined) {
                throw new RequiredError('audioId','Required parameter audioId was null or undefined when calling audioAudioIdGet.');
            }
            const localVarPath = `/audio/{audioId}`
                .replace(`{${"audioId"}}`, encodeURIComponent(String(audioId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication basic required

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {Audio} body Sending the parameters to transform the audio into text
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        audioPost: async (body: Audio, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling audioPost.');
            }
            const localVarPath = `/audio`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication basic required

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AudioApi - functional programming interface
 * @export
 */
export const AudioApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} audioId audioId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async audioAudioIdGet(audioId: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<TextFromAudio>>> {
            const localVarAxiosArgs = await AudioApiAxiosParamCreator(configuration).audioAudioIdGet(audioId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {Audio} body Sending the parameters to transform the audio into text
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async audioPost(body: Audio, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<TextFromAudio>>> {
            const localVarAxiosArgs = await AudioApiAxiosParamCreator(configuration).audioPost(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * AudioApi - factory interface
 * @export
 */
export const AudioApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @param {string} audioId audioId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async audioAudioIdGet(audioId: string, options?: AxiosRequestConfig): Promise<AxiosResponse<TextFromAudio>> {
            return AudioApiFp(configuration).audioAudioIdGet(audioId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {Audio} body Sending the parameters to transform the audio into text
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async audioPost(body: Audio, options?: AxiosRequestConfig): Promise<AxiosResponse<TextFromAudio>> {
            return AudioApiFp(configuration).audioPost(body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AudioApi - object-oriented interface
 * @export
 * @class AudioApi
 * @extends {BaseAPI}
 */
export class AudioApi extends BaseAPI {
    /**
     * 
     * @param {string} audioId audioId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AudioApi
     */
    public async audioAudioIdGet(audioId: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<TextFromAudio>> {
        return AudioApiFp(this.configuration).audioAudioIdGet(audioId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @param {Audio} body Sending the parameters to transform the audio into text
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AudioApi
     */
    public async audioPost(body: Audio, options?: AxiosRequestConfig) : Promise<AxiosResponse<TextFromAudio>> {
        return AudioApiFp(this.configuration).audioPost(body, options).then((request) => request(this.axios, this.basePath));
    }
}
