/* tslint:disable */
/* eslint-disable */
/**
 * Stability demo
 * Stability demo
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
// @ts-ignore
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import type { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH,  COLLECTION_FORMATS,  type RequestArgs,  BaseAPI, RequiredError } from '../base';
import type { Prompt } from '../models';
import type { PromptEnhanced } from '../models';
/**
 * Gpt3Api - axios parameter creator
 * @export
 */
export const Gpt3ApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {Prompt} body Sending the text to be enhanced
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        gpt3Post: async (body: Prompt, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling gpt3Post.');
            }
            const localVarPath = `/gpt3`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication basic required

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} promptEnhancedId promptEnhancedId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        gpt3PromptEnhancedIdGet: async (promptEnhancedId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'promptEnhancedId' is not null or undefined
            if (promptEnhancedId === null || promptEnhancedId === undefined) {
                throw new RequiredError('promptEnhancedId','Required parameter promptEnhancedId was null or undefined when calling gpt3PromptEnhancedIdGet.');
            }
            const localVarPath = `/gpt3/{promptEnhancedId}`
                .replace(`{${"promptEnhancedId"}}`, encodeURIComponent(String(promptEnhancedId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication basic required

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * Gpt3Api - functional programming interface
 * @export
 */
export const Gpt3ApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @param {Prompt} body Sending the text to be enhanced
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async gpt3Post(body: Prompt, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<PromptEnhanced>>> {
            const localVarAxiosArgs = await Gpt3ApiAxiosParamCreator(configuration).gpt3Post(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {string} promptEnhancedId promptEnhancedId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async gpt3PromptEnhancedIdGet(promptEnhancedId: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<PromptEnhanced>>> {
            const localVarAxiosArgs = await Gpt3ApiAxiosParamCreator(configuration).gpt3PromptEnhancedIdGet(promptEnhancedId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * Gpt3Api - factory interface
 * @export
 */
export const Gpt3ApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @param {Prompt} body Sending the text to be enhanced
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async gpt3Post(body: Prompt, options?: AxiosRequestConfig): Promise<AxiosResponse<PromptEnhanced>> {
            return Gpt3ApiFp(configuration).gpt3Post(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} promptEnhancedId promptEnhancedId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async gpt3PromptEnhancedIdGet(promptEnhancedId: string, options?: AxiosRequestConfig): Promise<AxiosResponse<PromptEnhanced>> {
            return Gpt3ApiFp(configuration).gpt3PromptEnhancedIdGet(promptEnhancedId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Gpt3Api - object-oriented interface
 * @export
 * @class Gpt3Api
 * @extends {BaseAPI}
 */
export class Gpt3Api extends BaseAPI {
    /**
     * 
     * @param {Prompt} body Sending the text to be enhanced
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof Gpt3Api
     */
    public async gpt3Post(body: Prompt, options?: AxiosRequestConfig) : Promise<AxiosResponse<PromptEnhanced>> {
        return Gpt3ApiFp(this.configuration).gpt3Post(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @param {string} promptEnhancedId promptEnhancedId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof Gpt3Api
     */
    public async gpt3PromptEnhancedIdGet(promptEnhancedId: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<PromptEnhanced>> {
        return Gpt3ApiFp(this.configuration).gpt3PromptEnhancedIdGet(promptEnhancedId, options).then((request) => request(this.axios, this.basePath));
    }
}
